### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [eduardorasgado/indecisionApp#1]
Hi @eduardorasgado, since I create two logos for your other projects, I would like to know if I can also create a design for this project?

Do you have something in your mind? How this app works? It´s for Android?

Best Regards!

**Comment by eduardorasgado** [comment]
Android/iOS :100:  I dont know maybe something like some animal, a sloth based logo for example bro :)

**Comment by zuurw** [comment]
Hi @eduardorasgado,

Yesterday I get inspired so I decide to design the logo for this project. For the concept I used the Sloth as inspiration, so I design a cute sloth face and as a reference to the name of the project e decide to add a question mark ? to de logo as a reference to the functionality of the indicision.

In this proposal I put app buttons to see how it looks, I dont know if this will be a android or iOs app.

And in the bottum of the proposal I put the logo with some colors variations, so now is up to you to decide if you like or not the logo :)

Best Regards!

![indecision proposal](https://user-images.githubusercontent.com/40801473/42998626-a93a5c50-8c12-11e8-9579-33caccab1d15.png)

**Comment by eduardorasgado** [comment]
Hey! That looks pretty good bro! The first one looks appropiate i think! Sweet! Send me a pull request bruh! Thanks.

**Comment by zuurw** [comment]
Hi @eduardorasgado I create the PR with the files I was going to put on the README.md, but you dony have it :)
Best Regards!

**Comment by eduardorasgado** [comment]
I have created the README.md, feel free to apply the changes to visualize the logo in README file :) Thanks @zuurw

**Comment by zuurw** [comment]
HI @eduardorasgado I made the PR with the README,md update.

Best Regards!
